nameOverride: ""
fullnameOverride: ""

image:
  pullPolicy: IfNotPresent

images:
  apiV1:
    repository: ghcr.io
    name: theshamuel/medregapi-v1
    tag: 2.0.1
  apiV2:
    repository: ghcr.io
    name: theshamuel/medregapi-v2
    tag: 1.0.0
  db:
    repository: ghcr.io
    name: theshamuel/medregdb
    tag: 2.0.0
  web:
    repository: ghcr.io
    name: theshamuel/medregweb
    tag: 2.0.1

tz: Europe/UTC

ingress:
  enabled: true
  eks:
    type: "alb"
  host: "medregistry.example.com"

web:
  service:
    type: ClusterIP
    port: 80
  replicas: 1
  probs:
    readiness:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 30
      successThreshold: 3
    liveness:
      initialDelaySeconds: 300
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 10
db:
  replicas: 1
  backups:
    import:
      enabled: false
      name: ""
    export:
      enabled: false
      secretName: s3-credentials-secret

apiV1:
  replicas: 1
  host: "dummy.com"
  port: 80
  reports:
    path: "/reports"

apiV2:
  replicas: 1
  host: "dummy.com"
  port: 80
  reports:
    path: "/reports"