logging:
  level:
    com.theshamuel: INFO
  file: /var/log/medregistry.log
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    banner-mode: "off"
endpoints:
  shutdown.enabled: true
management:
  security.enabled: false
server:
  port: 9000