{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "medregistry.name" . }}
  labels:
  {{- include "medregistry.labels" . | nindent 4 }}
  {{- if eq (lower .Values.ingress.eks.type) "alb" }}
  annotations:
  {{- include "medregistry.eks.albAnnotations" . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: {{ include "medregistry.name" . }}-frontend
                port:
                  number: 80
{{- end }}