{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "medregistry.name" . }}-ingress
  labels:
  {{- include "medregistry.labels" . | nindent 4 }}
  annotations:
  {{- if and (eq (lower .Values.ingress.eks.type) "alb") .Values.ingress.eks.enabled }}
  {{- include "medregistry.eks.albAnnotations" . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - secretName: medregistry-tls-secret
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "medregistry.name" . }}-svc
                port:
                  number: 80
{{- end }}