{{/*Deploy db site*/}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "medregistry.name" . }}-db
  labels:
  {{- include "medregistry.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "medregistry.labels" . | nindent 6 }}
  serviceName: "nginx"
  replicas: {{ .Values.db.replicas }}
  template:
    metadata:
      labels:
      {{- include "medregistry.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: mongo
          image: {{ .Values.images.db.repository }}/{{ .Values.images.db.name }}:{{ .Values.images.db.tag }}
          ports:
            - containerPort: 21017
              name: tcp
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.db.storage.class }}
        resources:
          requests:
            storage: {{ .Values.db.storage.size }}