apiVersion: v1
kind: Service
metadata:
  name: {{ include "medregistry.name" . }}-frontend
  labels:
  {{- include "medregistry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    selector:
      {{- include "medregistry.selectorLabels" . | nindent 4 }}