nameOverride: ""
fullnameOverride: ""

image:
  pullPolicy: IfNotPresent

images:
  web:
    repository: ghcr.io
    name: theshamuel/medregweb
    tag: 2.0.1

tz: Europe/UTC

ingress:
  enabled: true
  eks:
    enabled: false
    type: "alb"
  host: "medregistry.example.com"

web:
  service:
    type: ClusterIP
    port: 80
  replicas: 1
  probs:
    readiness:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 30
      successThreshold: 3
    liveness:
      initialDelaySeconds: 300
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 10